theme: minima
title: Ryans Investing Blog
Description: Investing Blog
permalink: https://rmschr12.github.io/Investing/:title/
name: BLOG OF RYAN
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
